#pragma once

#define WGX_VERSION_MAJOR       1
#define WGX_VERSION_MINOR       0
#define WGX_VERSION_PATCH       0
#define WGX_VERSION_BUILD       0
#define WGX_VERSION_COMMA       WGX_VERSION_MAJOR,WGX_VERSION_MINOR,WGX_VERSION_PATCH,WGX_VERSION_BUILD
#define WGX_VERSION_STRING      "1.0.1"
#define WGX_VERSION_WSTRING     L"1.0.1"

#define IDI_WGX_APP             1
#define IDI_SYSTRAY_UNLOCK      2
#define IDI_SYSTRAY_LOCK        3
#define IDI_IMPORT_FROM_QR      4
#define IDI_MENU_ADD            5
#define IDI_MENU_EDIT           6
#define IDI_MENU_EXIT           7
#define IDI_MENU_REMOVE         8
#define IDI_WG_OFF              9
#define IDI_WG_ON               10
#define IDI_WG_CONNECTING       11

#define IDS_APP_TITLE                   1000
#define IDS_TRAY_CONNECTED              1001
#define IDS_MANAGE_TUNNELS              1002
#define IDS_EXIT                        1003
#define IDS_TUNNEL_NAME                 1004
#define IDS_OK                          1005
#define IDS_CANCEL                      1006
#define IDS_ENTER_TUNNEL_NAME           1007
#define IDS_IMPORT_TUNNEL               1008
#define IDS_IMPORT_TUNNEL_FROM_FILE     1009
#define IDS_IMPORT_TUNNEL_FROM_QR       1010
#define IDS_FAILED_IMPORT_CONFIG        1011
#define IDS_FAILED_CREATE_CONFIG        1012
#define IDS_FAILED_WRITE_CONFIG         1013
#define IDS_FAILED_CAPTURE_SCREEN       1014
#define IDS_QR_NOT_RECOGNIZED           1015
#define IDS_QR_NOT_WIREGUARD_CONFIG     1016
#define IDS_ABOUT_WGX                   1017
#define IDS_ABOUT_TEXT                  1018
#define IDS_FILE                        1019
#define IDS_ABOUT                       1020
#define IDS_WGX_WIN_NOT_FOUND           1021
#define IDS_FAILED_START_WGX_WIN        1022
#define IDS_DELETE_TUNNEL               1023
#define IDS_DELETE_TUNNEL_PREFIX        1024
#define IDS_DELETE_TUNNEL_SUFFIX        1025
#define IDS_FAILED_DELETE_CONFIG        1026
#define IDS_FAILED_OPEN_CONFIG          1027
#define IDS_EDIT                        1028
#define IDS_DELETE                      1029
#define IDS_START                       1030
#define IDS_STOP                        1031
#define IDS_TUNNELS                     1032
#define IDS_INTERFACE                   1033
#define IDS_DNS                         1034
#define IDS_PEER                        1035
#define IDS_ENDPOINT                    1036
#define IDS_ALLOWED_IPS                 1037
#define IDS_TRANSFER                    1038
#define IDS_NO_TUNNEL_SELECTED          1039
#define IDS_PROCESS_STARTED             1040
#define IDS_PROCESS_STOPPED             1041
#define IDS_PROCESS_EXITED_PREFIX       1042
#define IDS_PROCESS_EXITED_SUFFIX       1043
#define IDS_FILTER_WIREGUARD_CONFIG     1044
#define IDS_FILTER_ALL_FILES            1045
